# set is the alias of set-option

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# enable mouse control
set -g mouse on

# start window numbers at 1 to match keyboard order with tmux order
set -g base-index 1

# unbind split pane
unbind '"'
unbind %

# set vi mode
set-window-option -g mode-keys vi
# monitor window
set-window-option -g monitor-activity on
set-window-option -g bell-action any

# background
set-option -g status-style fg=black,bg=white
set-option -g status-right '#[fg=white,bg=default]%l:%M:%S %p#[default] #[fg=blue]%m-%d %a'
setw -g window-status-current-format "#[fg=colour10,bg=brightmagenta] #I #[fg=colour8]#[bg=colour14] #W#F"
