# ===== terminal and history =====
set -g default-terminal "tmux-256color"
set -as terminal-features ",alacritty:RGB"

set -g history-limit 100000
set -g history-file ~/.tmux_history

# do not wait for escape sequence
set -sg escape-time 0

# display time (ms)
set -g display-time 3000

# ===== prefix and copy mode =====
unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# clear history
bind C-k clear-history \; display-message "history cleared"

# ===== mouse and index =====
set -g mouse on

set -g base-index 1
set -g renumber-windows on
setw -g pane-base-index 1

# use vi mode
set -g mode-keys vi

# ===== pane / window behavior =====
# use vim-style direction keys to switch pane, support long press to switch continuously
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# split pane: up / down / left / right
bind - split-window -v
bind \| split-window -h

# monitor window activity and bell
setw -g monitor-activity on
setw -g bell-action any

# ===== status bar =====
set -g status-interval 5

set -g status-left-length 20
set -g status-left '#[fg=colour136][#S:#I.#P] '
set -g status-right '#[fg=colour33]%d %b %Y #[fg=colour61]- #[fg=colour64]%I:%M %p #[fg=colour61]- #[fg=colour37]#([ -f $HOME/.name ] && cat $HOME/.name || hostname)'

# ===== color (Solarized 256)=====
set -g status-style "bg=colour235,fg=colour136"

setw -g window-status-style "fg=colour244"
setw -g window-status-current-style "fg=colour166"
setw -g window-status-activity-style "fg=colour61"
setw -g window-status-bell-style "fg=colour61"

set -g pane-border-style "fg=colour235"
set -g pane-active-border-style "fg=colour240"

set -g message-style "bg=colour235,fg=colour166"

# pane number display
set -g display-panes-active-colour "colour166"
set -g display-panes-colour "colour33"

# clock
setw -g clock-mode-colour "colour64"